### ISSUE TITLE
Contribute: Wheel for Python 3.9 under Windows 10 x64

### ISSUE THREAD

**Issue by evandrix** [manicmaniac/arc4#11]
[arc4-0.0.3-cp39-cp39-win_amd64.whl.zip](https://github.com/manicmaniac/arc4/files/5368376/arc4-0.0.3-cp39-cp39-win_amd64.whl.zip)

**Comment by manicmaniac** [comment]
@evandrix 

Thank you for your contribution.
However, I'm so sorry to say that I can't upload the built binary to PyPI for security reasons.

Instead, I built binary wheels for Windows and macOS by myself and uploaded to PyPI as version 0.0.4.
See https://pypi.org/project/arc4/0.0.4/#files.

I hope it helps.
